/*
 * Agent.Workbench REST - API
 * This is the REST-API for Agent.Workbench in an embbedded system mode.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@enflex.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ExecutionState model module.
 * @module model/ExecutionState
 * @version 1.0.0
 */
export class ExecutionState {
  /**
   * Constructs a new <code>ExecutionState</code>.
   * The Agent.Workbench execution state
   * @alias module:model/ExecutionState
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ExecutionState</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExecutionState} obj Optional instance to populate.
   * @return {module:model/ExecutionState} The populated <code>ExecutionState</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExecutionState();
      if (data.hasOwnProperty('executionMode'))
        obj.executionMode = ApiClient.convertToType(data['executionMode'], 'String');
      if (data.hasOwnProperty('deviceSystemExecutionMode'))
        obj.deviceSystemExecutionMode = ApiClient.convertToType(data['deviceSystemExecutionMode'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>executionMode</code> property.
 * @enum {String}
 * @readonly
 */
ExecutionState.ExecutionModeEnum = {
  /**
   * value: "APPLICATION"
   * @const
   */
  APPLICATION: "APPLICATION",

  /**
   * value: "SERVER"
   * @const
   */
  SERVER: "SERVER",

  /**
   * value: "SERVER_MASTER"
   * @const
   */
  SERVER_MASTER: "SERVER_MASTER",

  /**
   * value: "SERVER_SLAVE"
   * @const
   */
  SERVER_SLAVE: "SERVER_SLAVE",

  /**
   * value: "DEVICE_SYSTEM"
   * @const
   */
  DEVICE_SYSTEM: "DEVICE_SYSTEM"
};
/**
 * * 'APPLICATION' - Runs as end user application in an desktop environment * 'SERVER' - Runs as Background server-system * 'SERVER_MASTER' - Runs as central 'server. master' system and manages all 'server.slave' systems * 'SERVER_SLAVE' - Runs as central 'server. slave' system and wait for start order from the 'server.master' * 'DEVICE_SYSTEM' - Runs as system that directly executes single agents or projects 
 * @member {module:model/ExecutionState.ExecutionModeEnum} executionMode
 */
ExecutionState.prototype.executionMode = undefined;

/**
 * Allowed values for the <code>deviceSystemExecutionMode</code> property.
 * @enum {String}
 * @readonly
 */
ExecutionState.DeviceSystemExecutionModeEnum = {
  /**
   * value: "SETUP"
   * @const
   */
  SETUP: "SETUP",

  /**
   * value: "AGENT"
   * @const
   */
  AGENT: "AGENT"
};
/**
 * * 'SETUP' - Runs the selected setup of an AWB projekt * 'AGENT' - Runs one or more agents from an AWB project 
 * @member {module:model/ExecutionState.DeviceSystemExecutionModeEnum} deviceSystemExecutionMode
 */
ExecutionState.prototype.deviceSystemExecutionMode = undefined;

