/*
 * Agent.Workbench REST - API
 * This is the REST-API for Agent.Workbench in an embbedded system mode.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@enflex.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {KontaktformularInner} from './KontaktformularInner';

/**
 * The Kontaktformular model module.
 * @module model/Kontaktformular
 * @version 1.0.0
 */
export class Kontaktformular extends Array {
  /**
   * Constructs a new <code>Kontaktformular</code>.
   * @alias module:model/Kontaktformular
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>Kontaktformular</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Kontaktformular} obj Optional instance to populate.
   * @return {module:model/Kontaktformular} The populated <code>Kontaktformular</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Kontaktformular();
      ApiClient.constructFromObject(data, obj, 'KontaktformularInner');
    }
    return obj;
  }
}
