/*
 * Agent.Workbench REST - API
 * This is the REST-API for Agent.Workbench in an embbedded system mode.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@enflex.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The KontaktformularInner model module.
 * @module model/KontaktformularInner
 * @version 1.0.0
 */
export class KontaktformularInner {
  /**
   * Constructs a new <code>KontaktformularInner</code>.
   * @alias module:model/KontaktformularInner
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>KontaktformularInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/KontaktformularInner} obj Optional instance to populate.
   * @return {module:model/KontaktformularInner} The populated <code>KontaktformularInner</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new KontaktformularInner();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('vorname'))
        obj.vorname = ApiClient.convertToType(data['vorname'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('straße'))
        obj.strae = ApiClient.convertToType(data['straße'], 'String');
      if (data.hasOwnProperty('plz'))
        obj.plz = ApiClient.convertToType(data['plz'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
KontaktformularInner.prototype.name = undefined;

/**
 * @member {String} vorname
 */
KontaktformularInner.prototype.vorname = undefined;

/**
 * @member {String} email
 */
KontaktformularInner.prototype.email = undefined;

/**
 * @member {String} strae
 */
KontaktformularInner.prototype.strae = undefined;

/**
 * @member {Number} plz
 */
KontaktformularInner.prototype.plz = undefined;

