/*
 * Agent.Workbench REST - API
 * This is the REST-API for Agent.Workbench in an embbedded system mode.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@enflex.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The NetworkConnection model module.
 * @module model/NetworkConnection
 * @version 1.0.0
 */
export class NetworkConnection {
  /**
   * Constructs a new <code>NetworkConnection</code>.
   * Describes a single network connection.
   * @alias module:model/NetworkConnection
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>NetworkConnection</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NetworkConnection} obj Optional instance to populate.
   * @return {module:model/NetworkConnection} The populated <code>NetworkConnection</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NetworkConnection();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('macAddress'))
        obj.macAddress = ApiClient.convertToType(data['macAddress'], 'String');
      if (data.hasOwnProperty('ip4Addresses'))
        obj.ip4Addresses = ApiClient.convertToType(data['ip4Addresses'], 'String');
      if (data.hasOwnProperty('ip6Addresses'))
        obj.ip6Addresses = ApiClient.convertToType(data['ip6Addresses'], 'String');
      if (data.hasOwnProperty('trafficSendInMB'))
        obj.trafficSendInMB = ApiClient.convertToType(data['trafficSendInMB'], 'Number');
      if (data.hasOwnProperty('trafficReceivedInMB'))
        obj.trafficReceivedInMB = ApiClient.convertToType(data['trafficReceivedInMB'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
NetworkConnection.prototype.name = undefined;

/**
 * @member {String} displayName
 */
NetworkConnection.prototype.displayName = undefined;

/**
 * @member {String} macAddress
 */
NetworkConnection.prototype.macAddress = undefined;

/**
 * @member {String} ip4Addresses
 */
NetworkConnection.prototype.ip4Addresses = undefined;

/**
 * @member {String} ip6Addresses
 */
NetworkConnection.prototype.ip6Addresses = undefined;

/**
 * @member {Number} trafficSendInMB
 */
NetworkConnection.prototype.trafficSendInMB = undefined;

/**
 * @member {Number} trafficReceivedInMB
 */
NetworkConnection.prototype.trafficReceivedInMB = undefined;

