/*
 * Agent.Workbench REST - API
 * This is the REST-API for Agent.Workbench in an embbedded system mode.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@enflex.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {NetworkConnection} from './NetworkConnection';

/**
 * The SystemInformation model module.
 * @module model/SystemInformation
 * @version 1.0.0
 */
export class SystemInformation {
  /**
   * Constructs a new <code>SystemInformation</code>.
   * The system information consisting of Hardware and OS information
   * @alias module:model/SystemInformation
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SystemInformation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SystemInformation} obj Optional instance to populate.
   * @return {module:model/SystemInformation} The populated <code>SystemInformation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SystemInformation();
      if (data.hasOwnProperty('osDescription'))
        obj.osDescription = ApiClient.convertToType(data['osDescription'], 'String');
      if (data.hasOwnProperty('osManufacturer'))
        obj.osManufacturer = ApiClient.convertToType(data['osManufacturer'], 'String');
      if (data.hasOwnProperty('osFamilly'))
        obj.osFamilly = ApiClient.convertToType(data['osFamilly'], 'String');
      if (data.hasOwnProperty('osVersion'))
        obj.osVersion = ApiClient.convertToType(data['osVersion'], 'String');
      if (data.hasOwnProperty('processorName'))
        obj.processorName = ApiClient.convertToType(data['processorName'], 'String');
      if (data.hasOwnProperty('processorFrequenceInMhz'))
        obj.processorFrequenceInMhz = ApiClient.convertToType(data['processorFrequenceInMhz'], 'Number');
      if (data.hasOwnProperty('processorNoPhysical'))
        obj.processorNoPhysical = ApiClient.convertToType(data['processorNoPhysical'], 'Number');
      if (data.hasOwnProperty('processorNoLogical'))
        obj.processorNoLogical = ApiClient.convertToType(data['processorNoLogical'], 'Number');
      if (data.hasOwnProperty('memoryTotalInGB'))
        obj.memoryTotalInGB = ApiClient.convertToType(data['memoryTotalInGB'], 'Number');
      if (data.hasOwnProperty('swapMemoryTotalInGB'))
        obj.swapMemoryTotalInGB = ApiClient.convertToType(data['swapMemoryTotalInGB'], 'Number');
      if (data.hasOwnProperty('heapMemoryMaxInGB'))
        obj.heapMemoryMaxInGB = ApiClient.convertToType(data['heapMemoryMaxInGB'], 'Number');
      if (data.hasOwnProperty('networkConnections'))
        obj.networkConnections = ApiClient.convertToType(data['networkConnections'], [NetworkConnection]);
    }
    return obj;
  }
}

/**
 * @member {String} osDescription
 */
SystemInformation.prototype.osDescription = undefined;

/**
 * @member {String} osManufacturer
 */
SystemInformation.prototype.osManufacturer = undefined;

/**
 * @member {String} osFamilly
 */
SystemInformation.prototype.osFamilly = undefined;

/**
 * @member {String} osVersion
 */
SystemInformation.prototype.osVersion = undefined;

/**
 * @member {String} processorName
 */
SystemInformation.prototype.processorName = undefined;

/**
 * @member {Number} processorFrequenceInMhz
 */
SystemInformation.prototype.processorFrequenceInMhz = undefined;

/**
 * @member {Number} processorNoPhysical
 */
SystemInformation.prototype.processorNoPhysical = undefined;

/**
 * @member {Number} processorNoLogical
 */
SystemInformation.prototype.processorNoLogical = undefined;

/**
 * @member {Number} memoryTotalInGB
 */
SystemInformation.prototype.memoryTotalInGB = undefined;

/**
 * @member {Number} swapMemoryTotalInGB
 */
SystemInformation.prototype.swapMemoryTotalInGB = undefined;

/**
 * @member {Number} heapMemoryMaxInGB
 */
SystemInformation.prototype.heapMemoryMaxInGB = undefined;

/**
 * @member {Array.<module:model/NetworkConnection>} networkConnections
 */
SystemInformation.prototype.networkConnections = undefined;

