/*
 * Agent.Workbench REST - API
 * This is the REST-API for Agent.Workbench in an embbedded system mode.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@enflex.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {ExecutionState} from './model/ExecutionState';
import {Kontaktformular} from './model/Kontaktformular';
import {KontaktformularInner} from './model/KontaktformularInner';
import {NetworkConnection} from './model/NetworkConnection';
import {SystemInformation} from './model/SystemInformation';
import {SystemLoad} from './model/SystemLoad';
import {AdminsApi} from './api/AdminsApi';
import {DefaultApi} from './api/DefaultApi';

/**
* This_is_the_REST_API_for_Agent_Workbench_in_an_embbedded_system_mode_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var AgentworkbenchRestApi = require('index'); // See note below*.
* var xxxSvc = new AgentworkbenchRestApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new AgentworkbenchRestApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new AgentworkbenchRestApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new AgentworkbenchRestApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ExecutionState model constructor.
     * @property {module:model/ExecutionState}
     */
    ExecutionState,

    /**
     * The Kontaktformular model constructor.
     * @property {module:model/Kontaktformular}
     */
    Kontaktformular,

    /**
     * The KontaktformularInner model constructor.
     * @property {module:model/KontaktformularInner}
     */
    KontaktformularInner,

    /**
     * The NetworkConnection model constructor.
     * @property {module:model/NetworkConnection}
     */
    NetworkConnection,

    /**
     * The SystemInformation model constructor.
     * @property {module:model/SystemInformation}
     */
    SystemInformation,

    /**
     * The SystemLoad model constructor.
     * @property {module:model/SystemLoad}
     */
    SystemLoad,

    /**
    * The AdminsApi service constructor.
    * @property {module:api/AdminsApi}
    */
    AdminsApi,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
